version: "3.6"

services:
  server:
    build:
      context: ./
      dockerfile: Dockerfile
    command: bash -c "gunicorn app.flask_app:app --workers 1 --bind  0.0.0.0:8000"
    env_file:
      - .env
    ports:
      - 8000:8000

